### ISSUE TITLE
Recommend

### ISSUE THREAD

**Issue by charlotte-2222** [Necrocaustic/Thorn_Bot#1]
This line of code in [general use is self defeating](https://github.com/Necrocaustic/Thorn_Bot/blob/master/cogs/generaluse.py)
```
@commands.command(aliases=['statuwu','statowo'])
    async def status(self, ctx):
        """Tells the user the status of the bot."""
        await ctx.reply('Online and running: {}'.format(version)
```
Would recommend removing it. If the bot responds to a command, it is online and functioning. Bot status is really only useful in sharded bots where x out of y shards may be online

**Comment by Necrocaustic** [comment]
Yeah I know. That's the point. The bot either does or doesn't respond. I mainly also just use it for the version half of the command.
